services:
  connect:
    build:
      context: .
      dockerfile: Dockerfile.connect
    container_name: connect
    ports:
      - "8083:8083"
    restart: unless-stopped
    volumes:
      - ./secrets-src:/secrets-src:ro
      - ./connectors:/connectors:ro
    environment:
      KAFKA_URL: "kafka:9092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      SSL_KEY_PASSWORD: "changeit"
      CONNECT_GROUP_ID: "kafka-connect"
      CONNECT_CONFIG_STORAGE_TOPIC: "kafka-connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "kafka-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "kafka-connect-status"